### ISSUE TITLE
关于LFE阶段数据集加载的问题

### ISSUE THREAD

**Issue by SillyPigeon** [ZhangZ7112/PVA-CAS#3]
您好，很感谢您们分享相关的工作。
但是，我发现发布的代码并不全，请问LFE阶段的数据集要怎么加载呢？请问该如何做数据的预处理，我发现直接用sitk读入数据并转为三维数组输入网络训练会报如下错误。请帮忙说明下，谢谢~
![屏幕截图 2024-01-26 160703](https://github.com/ZhangZ7112/PVA-CAS/assets/19251255/a446a46a-8ecf-4877-9526-a06eda8c344d)

**Comment by SillyPigeon** [comment]
缺失的文件:
![image](https://github.com/ZhangZ7112/PVA-CAS/assets/19251255/02187b15-6256-4abc-9954-9fe9e62e3e68)

**Comment by ZhangZ7112** [comment]
1.关于您的报错
看图一的报错提示，貌似您使用的数据是二维的？如果是的话，可能需要对模型部分进行一定的修改，将代码中的3D模型改成2D的（如果需要的话，我们后续可以提供2D的模型版本）。目前提供的3D版本要求的输入是5维的[Batch, Channel, Depth, Hight, Width]。

2. 关于遗失的代码
遗失的代码（Dataload_patch）已经重新补充，并对之前的文件命名做了小幅度小改。

希望对您有所帮助。

**Comment by SillyPigeon** [comment]
> 1.关于您的报错 看图一的报错提示，貌似您使用的数据是二维的？如果是的话，可能需要对模型部分进行一定的修改，将代码中的3D模型改成2D的（如果需要的话，我们后续可以提供2D的模型版本）。目前提供的3D版本要求的输入是5维的[Batch, Channel, Depth, Hight, Width]。
> 
> 2. 关于遗失的代码
>    遗失的代码（Dataload_patch）已经重新补充，并对之前的文件命名做了小幅度小改。
> 
> 希望对您有所帮助。

非常感谢您们提供的信息，是的，目前直接输入的是二维切片数据与层数，这边将再次尝试，关于这个issue没有其他问题了，谢谢
